<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>GLOBAL SURF INDUSTRIES - LIFE IS BETTER WHEN YOU SURF</title>
         <?php 
		define( "HOME", "" ); 
		define( "IMAGES_DIR",   HOME . "images/" );
		include HOME . 'includes/geo-locator-script.inc'; 
		include HOME . 'includes/header-includes.inc'; 
		include HOME . 'includes/googleAnalyticsTrackingCode.inc'; 
	?>
    <META NAME='author' CONTENT="Global Surf Industries" >
    <META NAME='subject' CONTENT="global surf industries - life is better when your surf®" >
    <META NAME='Description' CONTENT="When Mark Kelly founded Global Surf Industries, back in 2002, he wanted a company mantra that each employee could relate to. Over the years those words have become the foundation of the company, a saying GSI bases many decisions on. We've discovered many others not only relate to our mantra, but thousands live their life by it.<br>LIFE IS BETTER WHEN YOU SURF®.">
    <META NAME='Classification' CONTENT="Global Surf Industries - the world's premier distributor of surfboards - find product information, local surfboard shops or buy surfboards online." >
    <META NAME='Keywords' CONTENT="surfboards, surfboard, surfing, longboards, mark kelly, fish, shortboards, funboards, stand up paddle boards,hayden cox, josh constable, richie lovett, steve walden, tom carroll, tom wegener, life is better when you surf" >
    <META NAME='Language' CONTENT='English' >
    <META HTTP-EQUIV='CACHE-CONTROL' CONTENT='PUBLIC' > 
    <META HTTP-EQUIV='Expires' CONTENT='never' >
    <META NAME='Copyright' CONTENT='global surf industries. All rights reserved.' >
    <META NAME='Designer' CONTENT='surfindustries.com' >
    <META NAME='Publisher' CONTENT='Mark Kelly, Mark Kelly, Global Surf Industries' >
    <META NAME='Revisit-After' CONTENT='4' >
    <META NAME='distribution' CONTENT='Global' >
    <META NAME='Robots' CONTENT='INDEX,FOLLOW' >
    <META NAME='country' CONTENT='USA, United States, United States Of America, America' >
    <META NAME='organization' content='Global Surf Industries' >
    <META NAME='viewport' CONTENT='width = device-width'>
    <link rel='SHORTCUT ICON' href='http://www.surfindustries.com/favicon.ico' >
    </head>
    <body class="scroll-assist">
        <!-- include header -->
        <?php include HOME . 'includes/header-nav-items.inc'; ?>
        
        <div class="main-container">
            <section class="page-title page-title-2 image-bg overlay ">
                <div class="background-image-holder">
                 <?php echo "<img src='" . IMAGES_DIR ."company-mantra-header.jpg' class='background-image' alt='Global Surf Industries - Life is Better When You Surf'>"; ?>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-10">
							<h2 class="uppercase mb8">LIFE IS BETTER WHEN YOU SURF<sup class="smallText">&#174;</sup></h2>
                            
                        </div>
                        
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            <section>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-10 col-sm-offset-1 text-center">
                            <h3 class="mb64 mb-xs-24">When Mark Kelly founded Global Surf Industries, back in 2002, he wanted a company mantra that each employee could relate to. Over the years those words have become the foundation of the company, a saying GSI bases many decisions on. We've discovered many others not only relate to our mantra, but thousands live their life by it.<br>LIFE IS BETTER WHEN YOU SURF<sup class="smallText">&#174;</sup>.</h3>
                            </div>
                        <div class="col-md-12 col-sm-10 ">
							 <div class="embed-video-container embed-responsive embed-responsive-16by9">
                                <iframe class="embed-responsive-item" src="https://youtube.com/embed/oQhRJt2eb_Q/?showinfo=0&rel=0" allowfullscreen="allowfullscreen"></iframe>
                            </div>
							<p class="regularText"><p>Surfing is vastly different than any other activity. No wave is ever the same, even waves created by humans vary by degree. By whatever force nature has conjured, the act of riding waves has an uncanny ability to turn any kind of day or situation around for the better.</p><p class="regularText"><strong>IT IS SCIENTIFICALLY PROVEN</strong><p>In his book, High Surf, author Tim Baker, a good friend of the GSI family, interviewed scientist Vezen Wu who was at Columbia University at the time. Vezen was convinced that the scientific explanation for the feelings of elation he experienced while surfing were due to the existence of negative ions from breaking waves, which had been proven in clinical experiments to elevate a person's mood.</p><p>Positive ions attract atmospheric pollutants, dust particles and harmful airborne matter. They are high in indoor work environments where computer screens and TVs are rampant. Negative ions, on the other hand, cancel out the effect of positive ions and clean the air, increasing the sense of wellbeing.</p><p class="regularText">Since the ocean surf is one of the largest natural sources of negative ions, created from water molecules rubbing over each other when waves break, Vezen hypothesized that a surfer's stoke could be explained by being immersed the ocean, surrounded by breaking waves which would release negative ions and could elevate mood by affecting brain chemistry.</p><p class="regularText">"The treatment for depression could become as easy as a day at the beach," Vezen told Tim. "Just the feeling of the water on you, diving and paddling, duck-diving your first wave, seeing a set come, turning around and stroking into it, that initial rush as you drop down the face, the jolts of acceleration as you go through the maneuvers - there's nothing like it. The only thing that actually comes close to riding waves is sex."</p>
							
							<p class="regularText"><strong>SURFERS FROM ALL WALKS OF LIFE AGREE SURFING MAKES THEM HAPPIER</strong></p><p class="regularText">
							A few years ago, GSI hosted a contest asking participants to explain in less than 250 words why surfing has improved their lives. Besides the fact the results were incredibly moving, what the surfers shared was revealing.</p><p class="regularText">From beginners to the most advanced professionals, surfing has changed lives in ways that aren't always talked about in magazines or surf books. Surfing creates confidence in everyday lives, binds families, helps people recover from a loss or a difficult situation, fills a need for the most addictive personalities, brings people closer to nature, and allows others to challenge themselves in real life after challenging themselves in the sea. It's also makes people feel a part of something bigger, a feeling that's a bit difficult to put into words.</p><p class="regularText">By working with a variety of non-profits, GSI has also discovered that surfing allows at-risk youth to gain confidence and form a stronger connection to nature. Surfing has provided a source of healing for people recovering from accidents, people with autism, people dealing with depression, and the list goes on. GSI has also learned about hundreds of couples and friends who met over a shared love of surfing, and whose love of the activity has created a bond that's made them stick together. Surfing makes people laugh. It makes people smile. It makes them humble. And it's really fun.</p>
                           
							<p class="regularText"><strong>CASE STUDIES</strong></p><p class="regularText">Recently, a GSI employee volunteered at a surf clinic to teach wounded veterans to surf. There was 20-year-old young man from Florida in her group. A former surfer, he had lost all mobility below his waist serving in the military, and wasn't sure he would ever surf again. With a bit of assistance from volunteers who helped position him on a board and paddled him out to the outside, he was able to ride an open-faced wave all the way from the outside to shore. While he had been very quiet before, the young veteran beamed and cheered all the way to shore. He told everyone around the act of riding that one wave was the most fun he had since his accident the year prior.</p><p class="regularText">"I started surfing five months ago at the age of 31. Before I surfed I would get anxious, worrying constantly about my health, my career, my relationship, what I wore, how I looked, and what people thought of me," wrote a woman from Perth, Australia, in the GSI contest a few years ago. "Then, I went for a couple of surfing lessons and something changed in me. I started to realize that the waves were here before me and they'll be here after me; that the ocean is so much bigger than all of us. Somehow that came as a huge relief; to realize how insignificant and fleeting my problems really were. When I'm in the water my mind feels clear. Even getting tossed around in the waves just reminds me that I'm not so breakable after all. Surfing makes me feel part of something bigger, something profoundly beautiful and timeless. All we have to do is enjoy it while we're here. I feel like I'm in the moment, and it feels so good to be here, finally."</p>
                           
							<p class="regularText"><strong>SURFING GIVES YOU BALANCE</strong></p><p class="regularText">"Surfing gives you balance. Not just the unique ability to stand on a form of liquid energy that has travelled hundreds or sometimes thousands of kilometers to meet you and provide you a completely unique thrill that can not be replicated, but rather a more balanced perspective," wrote another contestant, a gentleman from Florida. "You are better equipped to deal with the daily grind and the obstacles that life throws up at you. Sitting out the back watching the sunrise or set and looking out over the vast horizon of blue, you get the rare opportunity to think about the ocean and the planet and mull over your place in it. You don't necessary solve your problems, but it gives you a break and allows you to regain some balance and perspective. Surfing is the PERFECT great escape, healthy, adventurous, and best of all fun. It doesn't get any better than the refreshing feeling of the clear salt water rushing over you when you push through the lip of breaking wave, or taking the drop and screaming down the face of a set wave at speed. It brings you into the moment. Life without surfing wouldn't be just boring, it would empty, because surfing gives more to your life than simply catching a wave."</p><p class="regularText">Here is another example of a man from Australia who wrote an entry in GSI's contest saying that surfing brought his family together.</p><p class="regularText">"Who would think surfing could bring a family and community closer together? It all started when my son went to a surf school for a birthday party, then all he wanted for Christmas was a soft board. He was so enthusiastic and hassled me everyday to take him to the beach so he could practice and now he is getting pretty good and his sister is learning to surf too. It has changed the dynamics of our family, extended family and neighbors. We're not very good, but we are all doing it and having fun. We now live by the beach and travel searching for new places to surf. For our children to have their parents, grandparents, aunties, uncles, cousins and neighbors involved in a lifestyle sport like surfing, it has created a bond between everyone that we will share for life. Life is better now that WE all surf!!"</p><p class="regularText">One common thread GSI discovered is how many people wrote about the fact that surfing forces them to live life in the moment, something that takes monks and the most spiritual gurus, years to learn.</p>
                           
                            <p class="regularText"><strong>SURFING MAKES YOU LIVE IN THE MOMENT</strong></p><p class="regularText">"Life is better when I surf because it ultimately makes ME a better person," wrote a woman from New York. "I have only recently discovered my greatest passion and it has opened me up in so many ways. There is nothing else, which will keep me planted so securely in the moment, where no other ponderings, insecurities or frivolous thoughts can invade my mind. Normally when things got too tough I would give up and try something else, but with surfing I keep going and going. Dumped again and again, taking some serious poundings, always going back for more. It's helped me stand up for myself and speak my mind in my daily activities and interactions, by standing up for myself in the line up, not getting dropped in on or snaked, which seems to happen a lot if you're an average girl surfer. It has made me prove I can do things when others may doubt my ability. It has opened up my environmental, nature-loving side even more and set me in motion to affect this earth in a positive way. It is the most fulfilling way to spend time. Surfing is living."</p><p class="regularText">It's not just the sport, it's everything that happens before and after you surf as well.</p><p class="regularText">"Years ago as a kid, my sister went to surf camp, and showed me what she had learned when she came home," wrote a man from California. "Little did I know that it would become a major part of my life. Ditching school to be in the water even when the waves were not there was a must. I had given up surfing for collage, a family and work, but 25 years later I have found myself back in the water at 47, a little grey and a few pounds heavier. It gives me time to reflect, un-wind and think about how much this world has to offer. The water holds memories of time gone by when I was young. As I look out at the horizon, I can see the past, present and future of my life. Surfing is more than catching a wave, it is about the experience. Every time is a new experience."</p><p class="regularText">"Surfing makes my life better because I love it," wrote a woman from Cape Town. "I love the mechanics. I love the flow. I love the color. I love the risk and I love the reward. I love the tingle as the lip pitches forward. I love the burn, the arc, and the shadow. I love the taste. I love the tumble. I love the line. I love the bowl. I love the anticipation. I love heartache. I love concentration. I love the loneliness and the camaraderie. I love the dawn, the evening, and the mid-day sun. I love the humbling and the air of superiority. I love the tightness and the fly-away loose. I love the science and the study and the kamikaze. I love the planning and I love the lottery. I love the energy of earth as it flows through me. I love myself when I am surfing.</p>
                            
							<p class="regularText"><strong>SURFING MAKES US LIGHT-HEARTED</strong></p><p class="regularText">Of course, surfing also gives us a sense of humor. Egging friends on in the lineup, laughing at the worst wipeouts, being humbled by personal wipeouts, cheering on the best rides and smiling at the ridiculousness of mundane traffic after a perfect session, and the post nasal drip that comes at the most inopportune times afterwards, are more reasons why surfers continue to ride waves.</p><p class="regularText">"Sitting in a staff meeting I try to concentrate but am distracted by the itchy drying salt on my back left from my early morning pre-commitment surf," wrote a gentleman from South Australia. "The itch draws me in to a dreamy state, recalling the small glassy morning surf; the empty car park, everyone else heading to work and the cool morning sand just starting to warm in the sun. The first duck-dive cleared my head and eyes. For an hour or so I was immersed in nature, surrounded by sea life oblivious to human noise or activity. Not many people are privy to this experience. Stirred from my daydream, it's my turn to speak. I stand, open my folder and as I bend my head to read, a liter of the Southern ocean gushes out of my nasal passages. Life really is better when you surf."</p>
                           
                           <p class="regularText"><strong>THE BEGINNERS</strong></p><p class="regularText">The feeling of riding the first wave is like none other. The glow, the excitement, that rush of water moving underneath your feet has been described as many people's most memorable moments.</p><p class="regularText">"There's no better feeling than seeing that glow in someone's eyes when they catch their first wave," said Izzy Tihanyi, owner of Surf Diva, the original all-women's surf school. "I've seen women quit their jobs, end bad relationships, move states, and develop a lot more confidence just by riding a few waves."</p>
                           
                           <p class="regularText"><strong>THE FIRSTS</strong></p><p class="regularText">After that first wave, there's the first time you see dolphins, the first time you ride a face, the first time you do a bottom turn, your first cutback, your first barrel. Then it's your best wave, your best cutback, and your best barrel. You never stop trying to improve, and there's always something to learn and experience.</p><p class="regularText">In an interview, legendary surfer Mickey Munoz, once said he went into a barrel in the Mentawais and came out ten years younger. The barrel literally changed his body chemistry, he said.</p>
                           
                           <p class="regularText"><strong>HEALING</strong></p><p class="regularText">While it is said to be the fountain for eternal youth, or at least eternal stoke, surfing's healing properties continue to be noticed. Dave Rossman who runs Surfers for Autism said, "Life is better when the kids of Surfers For Autism surf because there is an overwhelming sense of accomplishment and pride. They totally get that they are achieving something on their own without the assistance of parents, therapists or caregivers and express it in ways like never before."</p><p class="regularText">Like Dave, Chris Rutgers from Outdoor Outreach, a non-profit that teaches at-risk youth to surf, has seen tremendous gains from kids learning to surf.</p><p class="regularText">"I think anyone who has had the opportunity to spend time connected to nature intuitively knows about the positive impact it has on us. The average American 11- to 14-years-old has nine hours of screen time each day. We are raising an entire generation of kids with no connection to the natural world. It's shameful. However, any surfer can tell you about their first wave. There may not be a purer expression of joy in the human experience than feeling yourself glide on a wave, the only thing separating you from the energy in that wave is an inch thick piece of foam. Giving that feeling to inner city kids many of whom have never seen the ocean or left a five-block radius in their entire lives is transformative. Not only does surfing take them out of their element but also it helps them prove they can do a sport many didn't even think they'd ever have access to. Their relationships with others improve, they do better in school, and they are more happy."</p><p class="regularText">Jesse Billauer, founder of Life Rolls On, a non-profit that takes people with spinal cord injuries surfing, is another strong believer is surfing's healing power. "When I am in the ocean it creates a sense of freedom for me that I don't get to feel anywhere else in the world. The unique beauty of each swell makes me crave the art of riding a wave. Surfing allows me to forget that I am paralyzed and allows me to feel independent which is a priceless feeling for me. Getting lost in my creative expressions as I ride each wave exactly how I want to ride it, confirms to me that Life is Better When You Surf.</p>
                           
							<p class="regularText"><strong>LASTLY, IT'S WHO WE ARE AND WHAT WE DO</strong></p><p class="regularText">Life is better when you surf has been GSI's company mantra since day one. It incorporates everything that the employees appreciate about their lives and the industry they love to work in. GSI only manufactures and market their surfboards to surfers or people who want to become surfers. Everyone at GSI from the shapers to the founder to the sales reps and customer service staff knows firsthand the difference surfing has made in their own lives. Most of all, we love sharing our passion for surfing with other surfers -- from beginners to pros and everything in between.</p><p class="regularText">Thank you for letting us enjoy the ride with you.</p>
                            
							</div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            
            
             <?php include HOME . 'includes/footer.inc'; ?>
            
        </div>
        <?php include HOME . 'includes/site-scripts.inc'; ?>
    </body>
</html>