 <div class="main-container">
            <section class="page-title page-title-4 image-bg overlay parallax">
                <div class="background-image-holder">
                    <img src='https://gsimaintest.surfindustries.com/TEST/images/tm-portal-header.jpg' class='background-image' alt='Global Surf Industries - TM Portal'>
                    
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 class="uppercase mb0">TM PORTAL</h3><h4>DIT Claim Form Confirmation</h4>
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            <section>
                <div class="container">
                    <div class="row">
                        <div class="col-md-9 col-md-push-3">
                            <div class="row">
                              <div class="portalTopText">
                              
                             from sent
                            
                            </div> 
                               
								
                                
							</div> 
                            <!--end of row-->
                            
                        </div>
                        <!--end form div-->
                         <!--begin side bar-->
                        <div class="col-md-3 col-md-pull-9 hidden-sm">
                          