<!-- header includes -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php
echo '<link href="'.HOME.'css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />';
echo '<link href="'.HOME.'css/theme-gunmetal.css?v3" rel="stylesheet" type="text/css" media="all" />';
echo '<link href="'.HOME.'css/custom.css?v20" rel="stylesheet" type="text/css" media="all" />';
echo '<link href="'.HOME.'css/themify-icons.css" rel="stylesheet" type="text/css" media="all" />';
?>
<link href='https://fonts.googleapis.com/css?family=Lato%7CRaleway:100,400,300,500,600,700%7COpen+Sans:400,500,600' rel='stylesheet' type='text/css'>
<!-- end header includes -->
<!--<script type="text/javascript" src="https://cdn.weglot.com/weglot.min.js"></script>
<script>
    Weglot.initialize({
        api_key: 'wg_7c9f1bda637dbba5e98c81146052b2c67'
    });
</script>-->

    
    


