<div class="nav-container">
            <a id="top"></a>
            <nav class="nav-centered">
                <div class="nav-utility">
                    <div class="module left">
                        <i class="ti-email">&nbsp;</i>
                        <span class="sub">info@surfindustries.com</span>
                    </div>
                    <div class="moduleTop left">
                        <i class="ti-mobile">&nbsp;</i>
                        <span class="sub">AUS 1300 765 897</span>
                    </div>
                    <div class="moduleTop left">
                        <i class="ti-mobile">&nbsp;</i>
                        <span class="sub">NZ 1300 765 897</span>
                    </div>
                    <div class="moduleTop left">
                        <i class="ti-mobile">&nbsp;</i>
                        <span class="sub">US 1300 765 897</span>
                    </div>
                    <div class="module right">
                        <span class="sub" STYLE="letter-spacing: 0.0625em;">FREE SHIPPING ON ALL WEB ORDERS&nbsp;&nbsp;</span>
                        <a class="btn btn-sm btn-filled" href="#">Buy Online</a>
                        <a class="btn btn-sm hidden-xs hidden-sm hidden-md" href="variant/builder.html">Subscribe</a>
                        
                    </div>
                </div>
                <div class="text-center">
                    <?php echo "<a href='".HOME."index.php'><img src='" . IMAGES_DIR ."logo-gsi-home.png' class='logo logo-dark' alt='Global Surf Industries'></a>"; ?>
                </div>
                <div class="nav-bar text-center">
                    <div class="module widget-handle mobile-toggle right visible-sm visible-xs">
                        <i class="ti-menu"></i>
                    </div>
                    <div class="module-group text-left">
                        <div class="module left">
                            <ul class="menu">
                                <li class="has-dropdown">
                                    <a href="#">
                                        SURFBOARDS
                                    </a>
                                    <ul class="mega-menu">
                                        <li>
                                            <ul>
                                                <li>
                                                <?php echo "<a class='titleHeading' href='".HOME."surfboards/surfboards-by-type.php'>TYPE</a>"; ?>
											    </li>
                                                <li>
                                                    <a href="xxx">Beginner</a>
                                                </li>
                                                <li>
                                                    <a href="xxx">Finless</a>
                                                </li>
                                                <li>
                                                 <?php echo "<a href='".HOME."surfboards/surfboard-type-fish.php'>Fish</a>"; ?>
                                                    
                                                </li>
                                                <li>
                                                    <a href="xxx">Mid Lengths</a>
                                                </li>
                                                <li>
                                                    <a href="xxx">Longboards</a>
                                                </li>
                                                <li>
                                                    <a href="xxx">Shortboards</a>
                                                </li>
                                                <li>
                                                    <a href="xxx">Tri Quads</a>
                                                </li>
                                                <br>
                                                <br>
                                                <li>
													<span class="title">SURFBOARD TECHNOLOGY</span>
                                                </li>
                                                <li>
													<span class="title">VOLUME CALCULATOR</span>
                                                </li>
                                                
                                            </ul>
                                        </li>
                                        <li>
                                            <ul>
                                                <li>
													<?php echo "<a class='titleHeading' href='".HOME."surfboards/7S.php'>7S</a>"; ?>
                                                </li>
                                                <li>
                                                    <a href="home-photography-2.html">Double Down - CV</a>
                                                </li>
                                                <li>
                                                    <a href="home-personal-portfolio.html">Superfish 3 - CV</a>
                                                </li>
                                                <li>
                                                    <a href="home-property.html">Superfish II - X2</a>
                                                </li>
                                                <br>
                                                <li>
													<?php echo "<a class='titleHeading' href='".HOME."surfboards/7S.php'>CREATIVE ARMY</a>"; ?>
                                                </li>
                                                <li>
                                                    <a href="home-photography-2.html">Huevo - PU</a>
                                                </li>
                                                <li>
                                                    <a href="home-personal-portfolio.html">Jive - PU</a>
                                                </li>
                                                <li>
                                                    <a href="home-property.html">Seahorse - PU</a>
                                                </li>
                                                <li>
                                                    <a href="home-resume.html">Taco - PU</a>
                                                    <span class="newLabel">New!</span>
                                                </li>
                                                <br>
                                                <li>
													<?php echo "<a class='titleHeading' href='".HOME."surfboards/7S.php'>GNARALOO</a>"; ?>
                                                </li>
                                                <li>
                                                    <a href="home-property.html">Beach Cruiser - soft</a>
                                                </li>
                                                <li>
                                                    <a href="home-photography-2.html">Fatty - soft</a>
                                                </li>
                                                <li>
                                                    <a href="home-personal-portfolio.html">Flounder Pounder - soft</a>
                                                </li>
                                               
                                               
                                                
                                                
                                            </ul>
                                        </li>
                                        <li>
                                            <ul>
                                               <li>
													<?php echo "<a class='titleHeading' href='".HOME."surfboards/7S.php'>HAYDENSHAPES</a>"; ?>
                                                </li>
                                                <li>
                                                    <a href="home-property.html">Hypto Krypto - FF (FCSII)</a>
                                                </li>
                                                <li>
                                                    <a href="home-photography-2.html">Hypto Krypto - FF (Futures)</a>
                                                </li>
                                                <li>
                                                    <a href="home-personal-portfolio.html">Plunder - FF</a>
                                                </li>
                                                <li>
                                                    <a href="home-personal-portfolio.html">White Noiz - FF</a>
                                                </li>
                                                <li>
                                                    <a href="home-personal-portfolio.html">Untitled - FF</a>
                                                    <span class="newLabel">New!</span>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <ul>
                                               <li>
													<?php echo "<a class='titleHeading' href='".HOME."surfboards/7S.php'>MODERN</a>"; ?>
                                                </li>
                                                <li>
                                                    <a href="home-photography.html">Blackbird - PU</a>
                                                </li>
                                                <li>
                                                    <a href="home-photography-2.html">Blackbird - X1</a>
                                                    <span class="newLabel">New!</span>
                                                </li>
                                                <li>
                                                    <a href="home-personal-portfolio.html">Blackbird - X2</a>
                                                </li>
                                                <li>
                                                    <a href="home-property.html">Double Wide - X1</a>
                                                </li>
                                                <li>
                                                    <a href="home-resume.html">Double Wide - X2</a>
                                                </li>
                                                <li>
                                                    <a href="home-winery.html">Highline - PU</a>
                                                </li>
                                                <li>
													<a href="home-winery.html">Highline - X1</a></span>
                                                    <span class="newLabel">New!</span>
                                                </li>
                                                <li>
                                                    <a href="index.html">Highline - X2</a>
                                                </li>
                                                <li>
                                                    <a href="home-default-2.html">Love Child - PU</a>
                                                </li>
                                                <li>
                                                    <a href="home-default-3.html">Retro - PU</a>
                                                </li>
                                                <li>
                                                    <a href="home-default-4.html">The Boss - PU</a>
                                                    <span class="newLabel">New!</span>
                                                </li>
                                                <li>
                                                    <a href="home-default-5.html">The Boss - X1</a>
                                                    <span class="newLabel">New!</span>
                                                </li>
                                                <li>
                                                    <a href="home-default-5.html">The Boss - X2</a>
                                                    <span class="newLabel">New!</span>
                                                </li>
                                                <li>
                                                    <a href="home-default-5.html">Wild Child - PU</a>
                                                    <span class="newLabel">New!</span>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <ul>
                                               <li>
													<?php echo "<a class='titleHeading' href='".HOME."surfboards/7S.php'>The Seagalss Project</a>"; ?>
                                                </li>
                                                <li>
                                                    <a href="home-property.html">Albacore - soft</a>
                                                </li>
                                                <br>
                                                <li>
                                                    <?php echo "<a class='titleHeading' href='".HOME."surfboards/7S.php'>Three Palms Board Co.</a>"; ?>
                                                </li>
                                                <li>
                                                    <a href="home-personal-portfolio.html">Surfboard - soft</a>
                                                </li>
                                                <li>
                                                    <a href="home-personal-portfolio.html">Surfboard - X3</a>
                                                </li>
                                                <br>
                                                <li>
                                                    <?php echo "<a class='titleHeading' href='".HOME."surfboards/7S.php'>Walden</a>"; ?>
                                                </li>
                                                <li>
                                                    <a href="home-personal-portfolio.html">Magic Model - PU</a>
                                                </li>
                                                <li>
                                                    <a href="home-personal-portfolio.html">Magic Model - X2</a>
                                                </li>
                                                <li>
                                                    <a href="home-personal-portfolio.html">Mega Magic 2 - SLX</a>
                                                </li>
                                                <li>
                                                    <a href="home-personal-portfolio.html">Mini Mega Magic 2 - SLX</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li class="has-dropdown">
                                    <a href="#">
                                        STAND UP PADDLEBOARDS
                                    </a>
                                    <ul class="mega-menu sup-mega-menu">
                                        <li>
                                            <ul>
                                                <li>
                                                    <?php echo "<a class='titleHeading' href='".HOME."surfboards/7S.php'>TYPE</a>"; ?>
                                                </li>
                                                <li>
                                                    <a href="page-about-us-1.html">ALL ROUNDER</a>
                                                </li>
                                                <li>
                                                    <a href="page-about-us-2.html">FLATWATER</a>
                                                </li>
                                                <li>
                                                    <a href="page-about-us-3.html">INFLATABLE</a>
                                                </li>
                                                <li>
                                                    <a href="page-services-1.html">SURF</a>
                                                </li>
                                                <li>
                                                    <a href="page-services-2.html">YOGA</a>
                                                </li>
                                                <li>
                                                    <a href="page-services-3.html">SUP PADDLES</a>
                                                </li>
                                                <br>
                                                <br>
                                                <li>
													<span class="title">SUP TECHNOLOGY</span>
                                                </li>
                                                <li>
													<span class="title">VOLUME CALCULATOR</span>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <ul>
                                                <li>
                                                    <?php echo "<a class='titleHeading' href='".HOME."surfboards/7S.php'>ADVENTURE PADDLEBOARDING</a>"; ?>
                                                </li>
                                                <li>
                                                    <a href="page-about-us-1.html">ALL ROUNDER - CX</a>
                                                    <span class="newLabel">New!</span>
                                                </li>
                                                <li>
                                                    <a href="page-login.html">ALL ROUNDER - MX</a>
                                                    <span class="newLabel">New!</span>
                                                </li>
                                                <li>
                                                    <a href="page-register.html">ALL ROUNDER- X1</a>
                                                </li>
                                                <li>
                                                    <a href="page-coming-soon.html">ALL ROUNDER - X2</a>
                                                </li>
                                                <li>
                                                    <a href="page-faq.html">EXPLORER 2 - CX</a>
                                                    <span class="newLabel">New!</span>
                                                </li>
                                                <li>
                                                    <a href="page-confirmation.html">EXPLORER 2 - X2</a>
                                                </li>
                                                <li>
                                                    <a href="page-countdown.html">FIFTY FIFTY - X1</a>
                                                </li>
                                                <li>
                                                    <a href="page-countdown-2.html">INFLATABLE SUP</a>
                                                </li>
                                                <li>
                                                    <a href="page-404.html">PROJECT Y - X2</a>
                                                </li>
                                                <li>
                                                    <a href="page-404.html">SEVENTY THIRTY - CX</a>
                                                    <span class="newLabel">New!</span>
                                                </li>
                                                <li>
                                                    <a href="page-404.html">SIXTY FORTY - MX</a>
                                                    <span class="newLabel">New!</span>
                                                </li>
                                                <li>
                                                    <a href="page-404.html">SIXTY FORTY - X1</a>
                                                </li>
                                                <li>
                                                    <a href="page-404.html">SIXTY FORTY - X2</a>
                                                </li>
                                            </ul>
										</li>
                                         <li>
                                             <ul>
                                                <li>
                                                    <?php echo "<a class='titleHeading' href='".HOME."surfboards/7S.php'>THREE PALMS BOARD CO.</a>"; ?>
                                                </li>
                                                <li>
                                                    <a href="page-about-us-1.html">SUP - soft</a>
                                                </li>
                                                <li>
                                                    <a href="page-login.html">SUP - X3</a>
                                                </li>
                                                <br>
                                                <br>
                                                <li>
                                                    <?php echo "<a class='titleHeading' href='".HOME."surfboards/7S.php'>TOM CARROLL PADDLE SURF</a>"; ?>
                                                </li>
                                                <li>
                                                    <a href="page-about-us-1.html">LONG GRAIN V2 - CX</a>
													<span class="newLabel">NEW!</span>
                                                </li>
                                                <li>
                                                    <a href="page-about-us-1.html">LOOOSE LEAF V2 - CX</a>
													<span class="newLabel">NEW!</span>
                                                </li>
                                                <li>
                                                    <a href="page-about-us-1.html">OUTER REEF - CX</a>
											    </li>
                                                
											</ul>
                                        </li>
                                    </ul>
                                </li>
                                <li class="has-dropdown">
                                    <a href="#">
                                        PADDLES
                                    </a>
                                    <ul class="mega-menu">
                                        <li>
                                            <ul>
                                                <li>
                                                    <span class="title">Elements</span>
                                                </li>
                                                <li>
                                                    <a href="elements-buttons.html">
                                                        <i class="ti-link"></i> Buttons</a>
                                                </li>
                                                <li>
                                                    <a href="elements-tabs.html">
                                                        <i class="ti-layout-tab"></i> Tabbed Content</a>
                                                </li>
                                                <li>
                                                    <a href="elements-progress.html">
                                                        <i class="ti-rocket"></i> Progress Bars</a>
                                                </li>
                                                <li>
                                                    <a href="elements-accordions.html">
                                                        <i class="ti-layout-accordion-separated"></i> Accordions</a>
                                                </li>
                                                <li>
                                                    <a href="elements-alerts.html">
                                                        <i class="ti-flag-alt"></i> Alerts</a>
                                                </li>
                                                <li>
                                                    <a href="elements-form-inputs.html">
                                                        <i class="ti-pencil-alt"></i> Form Inputs</a>
                                                </li>
                                                <li>
                                                    <a href="elements-countdown.html">
                                                        <i class="ti-alarm-clock"></i> Countdowns</a>
                                                </li>
                                                <li>
                                                    <a href="elements-modals.html">
                                                        <i class="ti-layout-slider-alt"></i> Modals</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <ul>
                                                <li>
                                                    <span class="title">Elements</span>
                                                </li>
                                                <li>
                                                    <a href="elements-pricing.html">
                                                        <i class="ti-money"></i> Pricing Tables</a>
                                                </li>
                                                <li>
                                                    <a href="elements-icon-boxes.html">
                                                        <i class="ti-eye"></i> Icon Boxes</a>
                                                </li>
                                                <li>
                                                    <a href="elements-widgets.html">
                                                        <i class="ti-layout-media-right"></i> Widgets</a>
                                                </li>
                                                <li>
                                                    <a href="elements-typography.html">
                                                        <i class="ti-text"></i> Typography</a>
                                                </li>
                                                <li>
                                                    <a href="elements-lists.html">
                                                        <i class="ti-list"></i> Lists</a>
                                                </li>
                                                <li>
                                                    <a href="elements-grid.html">
                                                        <i class="ti-view-grid"></i> Grid Structure</a>
                                                </li>
                                                <li>
                                                    <a href="elements-textimage.html">
                                                        <i class="ti-layout-list-large-image"></i> Text &amp; Image</a>
                                                </li>
                                                <li>
                                                    <a href="elements-intros.html">
                                                        <i class="ti-microphone"></i> Intro Sections</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <ul>
                                                <li>
                                                    <span class="title">Elements</span>
                                                </li>
                                                <li>
                                                    <a href="elements-titles.html">
                                                        <i class="ti-layout-cta-left"></i> Titles Left</a>
                                                </li>
                                                <li>
                                                    <a href="elements-titles-center.html">
                                                        <i class="ti-layout-cta-center"></i> Titles Center</a>
                                                </li>
                                                <li>
                                                    <a href="elements-video.html">
                                                        <i class="ti-video-clapper"></i> Video Inline</a>
                                                </li>
                                                <li>
                                                    <a href="elements-video-bg.html">
                                                        <i class="ti-video-clapper"></i> Video BG</a>
                                                </li>
                                                <li>
                                                    <a href="elements-video-slider.html">
                                                        <i class="ti-video-clapper"></i> Video Slider</a>
                                                </li>
                                                <li>
                                                    <a href="elements-galleries.html">
                                                        <i class="ti-gallery"></i> Image Galleries</a>
                                                </li>
                                                <li>
                                                    <a href="elements-parallax.html">
                                                        <i class="ti-layers"></i> Parallax</a>
                                                </li>
                                                <li>
                                                    <a href="elements-nav-light.html">
                                                        <i class="ti-menu-alt"></i> Nav Styles</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li class="has-dropdown">
                                    <a href="#">
                                        ACCESSORIES
                                    </a>
                                    <ul>
                                        <li class="has-dropdown">
                                            <a href="#">
                                                Contained
                                            </a>
                                            <ul>
                                                <li>
                                                    <a href="portfolio-grid-2col.html">
                                                        2 Columns
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="portfolio-grid.html">
                                                        3 Columns
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="portfolio-grid-4col.html">
                                                        4 Columns
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="has-dropdown">
                                            <a href="#">
                                                Wide
                                            </a>
                                            <ul>
                                                <li>
                                                    <a href="portfolio-wide-2col.html">
                                                        2 Columns
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="portfolio-wide.html">
                                                        3 Columns
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="portfolio-wide-4col.html">
                                                        4 Columns
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="portfolio-parallax.html">
                                                Parallax
                                            </a>
                                        </li>
                                        <li class="has-dropdown">
                                            <a href="#">
                                                Single
                                            </a>
                                            <ul>
                                                <li>
                                                    <a href="portfolio-single-1.html">
                                                        Case Study 1
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="portfolio-single-2.html">
                                                        Case Study 2
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="portfolio-single-3.html">
                                                        Case Study 3
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="portfolio-single-4.html">
                                                        Case Study 4
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="portfolio-single-5.html">
                                                        Case Study 5
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li class="has-dropdown">
                                    <a href="#">
                                        HOW TO
                                    </a>
                                    <ul>
                                        <li class="has-dropdown">
                                            <a href="#">
                                                Shop Layout
                                            </a>
                                            <ul>
                                                <li>
                                                    <a href="shop-sidebar.html">
                                                        Sidebar Left
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="shop-sidebar-right.html">
                                                        Sidebar Right
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="shop-fullwidth-4col.html">
                                                        4 Columns
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="shop-fullwidth.html">
                                                        3 Columns
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="shop-fullwidth-2col.html">
                                                        2 Columns
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="has-dropdown">
                                            <a href="#">
                                                Product Single
                                            </a>
                                            <ul>
                                                <li>
                                                    <a href="shop-product-sidebar-left.html">
                                                        Sidebar Left
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="shop-product-sidebar.html">
                                                        Sidebar Right
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="shop-product-fullwidth.html">
                                                        No Sidebar
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="shop-cart.html">
                                                Cart
                                            </a>
                                        </li>
                                        <li>
                                            <a href="shop-checkout.html">
                                                Checkout
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <?php echo "<a href='".HOME."blog/index.php'>BLOG</a>"; ?>
                                    
                                </li>
                                <li class="has-dropdown">
                                    <a href="#">
                                        LOGIN
                                    </a>
                                    <ul>
                                        <li>
                                           <?php echo "<a href='".HOME."TM-portal/tm-portal-login.php'>TM Portal</a>"; ?>
                                        </li>
                                    </ul>
                                </li>
                                <li class="has-dropdown">
                                    <a href="#">
                                        STOCKISTS
                                    </a>
                                    <ul>
                                        <li class="has-dropdown">
                                            <a href="#">
                                                Listing
                                            </a>
                                            <ul>
                                                <li>
                                                    <a href="blog-sidebar.html">
                                                        Sidebar Left
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="blog-sidebar-right.html">
                                                        Sidebar Right
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="blog-no-sidebar.html">
                                                        No Sidebar
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="has-dropdown">
                                            <a href="#">
                                                Masonry
                                            </a>
                                            <ul>
                                                <li>
                                                    <a href="blog-masonry-sidebar.html">
                                                        Sidebar Left
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="blog-masonry-sidebar-right.html">
                                                        Sidebar Right
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="blog-masonry.html">
                                                        3 Columns
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="blog-masonry-2col.html">
                                                        2 Columns
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="has-dropdown">
                                            <a href="#">
                                                Single
                                            </a>
                                            <ul>
                                                <li>
                                                    <a href="blog-single-sidebar.html">
                                                        Sidebar Left
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="blog-single-sidebar-right.html">
                                                        Sidebar Right
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="blog-single-no-sidebar.html">
                                                        No Sidebar
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="blog-single-disqus.html">
                                                        Disqus Comments
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="blog-simple-feed.html">
                                                Simple Feed
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="has-dropdown">
                                    <a href="#">
                                        CONTACT US
                                    </a>
                                       
                                            <ul>
                                                <li>
												    <?php echo "<a href='".HOME."contacts/contacts-australia.php'>AUSTRALIAN CONTACTS</a>"; ?></li>
                                                <li>
                                                    <?php echo "<a href='".HOME."contacts/contacts-new-zealand.php'>
                                                        NEW ZEALAND CONTACTS
                                                    </a>"; ?>
                                                </li>
                                                <li>
                                                    <?php echo "<a href='".HOME."contacts/contacts-usa.php'>
                                                        US CONTACTS
                                                    </a>"; ?>
                                                </li>
												<li>
                                                    <?php echo "<a href='".HOME."contacts/contacts-worldwide.php'>WORLDWIDE CONTACTS   </a>"; ?>
                                                </li>
                                            </ul>
                                        
                                       
                                       
                                    
                                </li>
                            </ul>
                        </div>
                        <!--end of menu module-->
                       
                        
                        
                    </div>
                    <!--end of module group-->
                </div>
            </nav>
        </div>